# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c03b845fb5d90a04f94a02e7944591f0237124457010d2e6f79b61c3c5ebb9b47f48d497363adab278c70624bc22778c51912e1480da8d68bccd91bb45154f1d

test:
  secret_key_base: 312a030a43bd3486d99484fed27d47536a1a53a240d9b4d82aff957b87d8b691eb76dbc1467cd700449e814da43cf730b55af7929047780f2395d4b149473911

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
